#!/bin/bash
# $Id: m2txt,v 1.7 2016/03/03 10:25:53 fulford Exp fulford $
# $Source: /src/merlin/usr/local/etc/RCS/m2txt,v $
# $Revision: 1.7 $
# Author C W Fulford.
# Copyright 2016 (c) C W Fulford.
# Licensed for public use under the LGPL, .
# For assistance contact fulford@fulford.net 0709 229 5385
########################################################################
cmd=`basename $0`
ver=`echo "$Id: m2txt,v 1.7 2016/03/03 10:25:53 fulford Exp fulford $"|awk '{print $3,$4,$5}'`
syntax="$cmd [-c <configfile>] [-d] [-h <hostid>] [-v]|-V"
while [ $# -gt 0 ] ;do
	case $1 in 
		-c) config=$2;shift 2;;
		-d) set -x;debug=0;shift;;
		-v) verbose=:;shift;;
		-V) echo "$cmd $Revision: 1.7 $ $Date: 2016/03/03 10:25:53 $"|
		    awk '{print $1,$3,$6}'
	 	    exit;;  
		 *) subject="$subject $1";shift;;
	esac
done
txt=07935728612@txtlocal.co.uk

config=${config:-/usr/local/etc/${cmd}.cf}
#[ -r $config ]||{echo $cmd: Can't find $config;exit 1}
#eval `sed <$config -ne "/^$hostid:/,/^$/{/^[\t ]*[^#].*/p}"`
mailx -s "$subject" $txt </dev/null
